services:
  postgres:
    image: postgres:16-alpine
    container_name: gojo-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gojo
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations/001_initial-schema.sql:/docker-entrypoint-initdb.d/001_initial-schema.sql

  redis:
    image: redis:7-alpine
    container_name: gojo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
